const data=[
{id:'bio',name:'차바이오텍',ticker:'085660',g:'B',event:'CGT(세포·유전자치료제) 글로벌 사업 가시성 확대',tags:['Growth ↑','CGT/CDMO','Matica'],thesis:'글로벌 CGT 사업 확장성과 CDMO 수주 가시성 중심 모니터링',kpis:[['Matica 수주','TBD'],['추가 자금조달','없음'],['CGT 파이프라인','Watch'],['Thesis','유지']],events:['미국 CGT 사업 관련 기사 노출','마티카바이오 수주·임상 파이프라인 지속 점검'],watch:['마티카바이오 CGT CDMO 수주 계약','유상증자·CB 등 추가 자금조달','CGT 임상 파이프라인 진척']},
{id:'ai',name:'차AI헬스케어',ticker:'025620',g:'A',event:'반기보고서: 투자자산 확대·본업 영업적자 지속',tags:['Profitability ↓','Liquidity ↓','카카오헬스케어'],thesis:'헬스케어 플랫폼 전환은 진행 중이나 투자자산 가치와 자금조달 리스크가 핵심',kpis:[['매출','48.5억'],['영업손익','△35.0억'],['현금','108.7억'],['관계기업투자','700.4억']],events:['카카오헬스케어 150억원 추가 취득','인빅터스재팬헬스케어펀드 신규 투자','현금 감소 및 CB 확대'],watch:['카카오헬스케어 영업적자 축소','추가 CB/유상증자 여부','헬스케어 자체 매출 발생','그룹 내 성장자산 Value Flow']},
{id:'lumn',name:'루멘',ticker:'(미국)',g:'C',event:'주요 변동 없음',tags:['벤치마크','IFP 성장률','Loss Ratio'],thesis:'투자 검토 대상 벤치마크. 밸류에이션 매력도와 손해율(Loss Ratio) 개선 추이가 핵심 관전 포인트',kpis:[['IFP 성장률','Watch'],['Loss Ratio','Watch'],['EBITDA 흑자전환','Watch'],['52주 고점대비','-9.3%']],events:['공시·기사 기준 특이사항 없음'],watch:['투자 검토 관점의 밸류에이션 매력도','IFP·Loss Ratio 등 핵심 지표 추이','당사 사업모델과의 시사점']},
{id:'lgi',name:'Lippo General Insurance',ticker:'LPGI',g:'C',event:'주요 변동 없음',tags:['관계사','OJK','PIKK'],thesis:'인니 관계사. OJK 규제 변화와 자본적정성, PIKK 개정 동향이 핵심 관전 포인트',kpis:[['GWP 성장률','Watch'],['손해율(CR)','Watch'],['자본적정성(RBC)','Watch'],['52주 고점대비','-33.9%']],events:['공시·기사 기준 특이사항 없음'],watch:['OJK 규제 변화','자본적정성(RBC) 동향','PIKK 개정 관련 동향']}
];
const list=document.getElementById('list');
function render(f='ALL'){let arr=data.filter(x=>f==='ALL'||x.g===f);list.innerHTML=arr.map(x=>`<div class="card" data-id="${x.id}"><div class="top"><div><div class="name">${x.name}</div><div class="ticker">${x.ticker}</div></div><span class="badge ${x.g}">${x.g}급</span></div><div class="event">${x.event}</div><div class="tags">${x.tags.map(t=>`<span class="tag">${t}</span>`).join('')}</div></div>`).join('');document.querySelectorAll('.card').forEach(c=>c.onclick=()=>detail(c.dataset.id))}
function detail(id){const x=data.find(v=>v.id===id);document.getElementById('detail').innerHTML=`<div class="dt">${x.name}</div><div class="dd">${x.thesis}</div><div class="sec"><h4>Key KPI</h4><div class="kpis">${x.kpis.map(k=>`<div class="kpi"><span>${k[0]}</span><b>${k[1]}</b></div>`).join('')}</div></div><div class="sec"><h4>Recent Events</h4>${x.events.map(e=>`<div class="tl">${e}</div>`).join('')}</div><div class="sec"><h4>Current Watch Point</h4><ul>${x.watch.map(w=>`<li>${w}</li>`).join('')}</ul></div>`;document.getElementById('backdrop').classList.add('open');if(window.Telegram?.WebApp?.HapticFeedback)Telegram.WebApp.HapticFeedback.impactOccurred('light')}
document.getElementById('close').onclick=()=>document.getElementById('backdrop').classList.remove('open');
document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{document.querySelectorAll('.chip').forEach(x=>x.classList.remove('on'));b.classList.add('on');render(b.dataset.f)});
const d=new Date();document.getElementById('today').textContent=`${d.getFullYear()}.${String(d.getMonth()+1).padStart(2,'0')}.${String(d.getDate()).padStart(2,'0')}`;
document.getElementById('aCnt').textContent=data.filter(x=>x.g==='A').length;document.getElementById('bCnt').textContent=data.filter(x=>x.g==='B').length;document.getElementById('cCnt').textContent=data.filter(x=>x.g==='C').length;
if(window.Telegram?.WebApp){Telegram.WebApp.ready();Telegram.WebApp.expand();}
render();